<a href="https://colab.research.google.com/github/sadia4444a/Machine-Learning-project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
from time import process_time

In [5]:
np_arry=np.array([i for i in range(100000)])

start_time=process_time()

np_arry+=5

end_time = process_time()

print(end_time-start_time)

0.00041141199999983336


In [6]:
#list

list1=[1,2,3,4,5,6]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5, 6]
<class 'list'>


numpy arrays


In [7]:
np_array=np.array([1,2,3,4,5,6,7])
print(np_array)
type(np_array)
np_array.shape

[1 2 3 4 5 6 7]


(7,)

In [8]:
#creating tow dimension array

b=np.array([(1,2,3,4),(5,6,7,8),(8,9,7,6),(3,5,4,5)])
print(b)
type(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]
 [8 9 7 6]
 [3 5 4 5]]


(4, 4)

In [9]:
c=np.array([(1,2,3,4),(7.4,7.9,9.8,12.4)],dtype=float)
print(c)

[[ 1.   2.   3.   4. ]
 [ 7.4  7.9  9.8 12.4]]


In [10]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
y=np.ones((5,6))
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [12]:
z=np.full((5,10),5)
print(z)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [13]:
a=np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [14]:
b=np.random.random((3,4))
print(b)

[[0.06047425 0.45129556 0.8954331  0.65715641]
 [0.77903001 0.17702248 0.0565324  0.83169232]
 [0.45206194 0.22091932 0.47466961 0.34873418]]


In [15]:
c = np.random.randint(10,100,(6,9))
print(c)

[[59 96 95 62 49 76 10 70 40]
 [34 93 70 29 31 24 32 28 29]
 [77 68 75 57 18 26 56 35 76]
 [48 42 66 58 10 96 68 40 33]
 [73 92 90 66 15 88 64 77 87]
 [77 69 40 17 67 87 11 69 68]]


In [16]:
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [17]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [18]:
python_list=[i for i in range(100000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time = process_time()

print(end_time-start_time)

0.012040692000000242


In [19]:
list2=[1,2,3,4,5]
list1=np.asarray(list2)
print(list1)

[1 2 3 4 5]


In [20]:
c=np.random.randint(10,90,(10,10))
print(c)

[[66 88 84 10 23 65 70 59 15 27]
 [70 29 27 21 31 12 63 41 72 28]
 [40 59 81 15 59 57 89 17 23 16]
 [74 77 87 30 24 38 11 29 54 70]
 [83 67 42 46 32 23 53 84 29 53]
 [80 80 29 51 49 47 30 30 61 10]
 [32 47 47 32 44 16 85 36 34 48]
 [84 42 50 59 66 27 38 73 58 87]
 [38 76 33 34 63 21 74 45 13 53]
 [88 46 15 42 73 22 48 89 11 60]]


In [21]:
print(c.shape)


(10, 10)


In [22]:
print(c.ndim)

2


In [23]:
print(c.size)

100


In [24]:
print(c.dtype)

int64


In [25]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [26]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [27]:
print(a)
print(b)

[[1 1 3]
 [6 3 3]
 [5 3 8]]
[[19 16 14]
 [16 15 19]
 [10 17 12]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 17 17]
 [22 18 22]
 [15 20 20]]
[[-18 -15 -11]
 [-10 -12 -16]
 [ -5 -14  -4]]
[[19 16 42]
 [96 45 57]
 [50 51 96]]
[[0.05263158 0.0625     0.21428571]
 [0.375      0.2        0.15789474]
 [0.5        0.17647059 0.66666667]]


In [30]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[27 23 16]
 [19 13 21]
 [21 18 24]]
[[-11 -15 -10]
 [-11 -13 -17]
 [-11 -10  -6]]
[[152  76  39]
 [ 60   0  38]
 [ 80  56 135]]
[[0.42105263 0.21052632 0.23076923]
 [0.26666667 0.         0.10526316]
 [0.3125     0.28571429 0.6       ]]


In [34]:
ar=np.random.randint(0,10,(2,3))
print(ar)
print(ar.shape)

[[1 9 1]
 [0 7 1]]
(2, 3)


In [36]:
trans=np.transpose(ar)
print(trans)


[[1 0]
 [9 7]
 [1 1]]


In [37]:
trans2=ar.T
print(trans2)

[[1 0]
 [9 7]
 [1 1]]


In [38]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 8 6]
 [2 7 1]]
(2, 3)


In [40]:
b=a.reshape(3,2)
print(b)

[[8 8]
 [6 2]
 [7 1]]
